import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AppLayout } from "@/components/ui/AppLayout";
import { NotificationsProvider } from '@/utils/notifications';
import { SyncProvider } from '@/utils/sync';
import { AuthGuard } from '@/utils/auth-guard';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ru">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        style={{
          minHeight: "100dvh",
          background: "var(--background)",
          margin: 0,
          padding: 0,
          boxSizing: "border-box",
          overflowX: "hidden",
        }}
      >
        <AuthGuard>
        <SyncProvider>
            <NotificationsProvider>
                <AppLayout>{children}</AppLayout>
            </NotificationsProvider>
        </SyncProvider>
        </AuthGuard>
      </body>
    </html>
  );
}